version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"

  actionserviceapi.web:
    image: ${DOCKER_REGISTRY-}actionserviceapiweb
    build:
      context: .
      dockerfile: src/Services/Action/ActionServiceAPI.Web/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  identityserviceapi:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      
  warehouseserviceapi:
    image: ${DOCKER_REGISTRY-}warehouseserviceapi
    build:
      context: .
      dockerfile: src/Services/Warehouse/WarehouseServiceAPI/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
