version: '3.4'

name: "MaintenancePlanner"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: sqlserver

  jwtauthenticationapp:
    image: ${DOCKER_REGISTRY-}jwtauthenticationapp
    build:
      context: .
      dockerfile: src/Auxiliaries/Authentication/JwtAuthenticationApp/Dockerfile

  actionserviceapi.web:
    image: ${DOCKER_REGISTRY-}actionserviceapiweb
    container_name: ActionServiceAPI
    build:
      context: .
      dockerfile: src/Services/Action/ActionServiceAPI.Web/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  identityserviceapi:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    container_name: IdentityServiceAPI
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq      
      
  warehouseserviceapi:
    image: ${DOCKER_REGISTRY-}warehouseserviceapi
    container_name: WarehouseServiceAPI
    build:
      context: .
      dockerfile: src/Services/Warehouse/WarehouseServiceAPI/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq      

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: src/Gateways/OcelotGateway/Dockerfile
    depends_on:
      - actionserviceapi.web
      - identityserviceapi
      - warehouseserviceapi
      - jwtauthenticationapp