version: '3.4'

name: "MaintenancePlanner"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd112345678"
      ACCEPT_EULA: "Y"

  actionserviceapi.web:
    image: ${DOCKER_REGISTRY-}actionserviceapiweb
    container_name: ActionServiceAPI
    build:
      context: .
      dockerfile: src/Services/Action/ActionServiceAPI.Web/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  identityserviceapi:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    container_name: IdentityServiceAPI
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      
  warehouseserviceapi:
    image: ${DOCKER_REGISTRY-}warehouseserviceapi
    container_name: WarehouseServiceAPI
    build:
      context: .
      dockerfile: src/Services/Warehouse/WarehouseServiceAPI/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: src/Gateways/OcelotGateway/Dockerfile
    depends_on:
      - actionserviceapi.web
      - identityserviceapi
      - warehouseserviceapi
